### ISSUE TITLE
How to update value in cell component

### ISSUE THREAD

**Issue by steffenbrem** [offirgolan/ember-light-table#157]
What is the recommended way to update the value of a cell inside a cell component? Currently it is marked as read only. I need this since I have an `editable-cell` component in which you can update the value to something else.

This is the best I could come up with:

```js
rawValue: Ember.computed({
    get() {
        return this.get('row.'+this.get('column.valuePath'));
    },
    set(key, value) {
        return this.set('row.'+this.get('column.valuePath'), value);
    }
})
```

**Comment by offirgolan** [comment]
@steffenbrem are you not able to just use `rawValue` directly?

```hbs
{{input value=rawValue}}
```

**Comment by steffenbrem** [comment]
@offirgolan No, since this is only defined on the base cell, it is not passed to the actual cell component instance. See: https://github.com/offirgolan/ember-light-table/blob/master/addon/templates/components/cells/base.hbs#L2

**Comment by offirgolan** [comment]
Oh man.. ill make sure to add the `rawValue` to the custom component in the next iteration. 

In the mean time, you can do something like this in your custom component

```js
init() {
  this._super(...arguments);
  Ember.defineProperty(this, 'rawValue', Ember.computed.alias(`row.${this.get('column.valuePath')}`);
}
```

**Comment by offirgolan** [comment]
Resolved with #163

**Comment by steffenbrem** [comment]
@offirgolan I am using the latest master right now, but I am still unable to update the value directly. For example this checkbox, it will not update the property on the model:

```hbs
{{input type="checkbox" checked=value}}
{{input type="checkbox" checked=rawValue}}
```

**Comment by offirgolan** [comment]
@steffenbrem unfortunately the `value` and `rawValue` properties cannot be bound. The only way to do that is adding a `defineProperty` on init which causes huge performance problems. 

I would suggest using one of the solutions I posted above.

**Comment by redbmk** [comment]
The way I solved this was to add an observer - is there a benefit to using ember-one-way-controls instead?

Basically I just did:
```
  updateRawValue: Ember.observer('value', function() {
    this.set(`row.${this.get('column.valuePath')}`, this.get('value'));
  })
```

**Comment by offirgolan** [comment]
@redbmk `ember-one-way-controls` sends an action when the input's value changes which allows you to use the DDAU ideology instead of observers.

**Comment by JensNordenbro** [comment]
I also had to do as @redbmk, any progress on this @offirgolan  ?
