### ISSUE TITLE
The result of a server query is immutable

### ISSUE THREAD

**Issue by dmtask** [offirgolan/ember-light-table#423]
We use the Ember LightTable for our standard table view. The data for these tables come via remote interface from the server. Now it is so that we have a search, use the Endlessscrolling the LightTable and still have sorting.

Normaly it´s no problem. However, if we have now reloaded data, if the user was at the end of the page and would like to search something, the following error occurs:
![bildschirmfoto 2017-06-12 um 15 27 05](https://user-images.githubusercontent.com/17166931/27037442-448854e6-4f88-11e7-84cd-dff1d04fa5cc.png)

That's silly. I'm assuming that the `{enableSync: this.get ('enableSync')}`. However, the reloading of data does not work without. Does anyone have an idea how to connect everything and can work with each server side requests?

If you want to see more code, let me know.

**Comment by buschtoens** [comment]
Did you have a look at the [Cookbook](https://offirgolan.github.io/ember-light-table/#/cookbook/client-side)?

And for a quick fix: I assume you have something like this.

```js
fetchData(page) {
  get(this, 'store').query('foo-model', { page }).then((data) => {
    this.set('model', data);
  });
}
```

Just append a `.toArray()` to the API response.


```js
fetchData(page) {
  get(this, 'store').query('foo-model', { page }).then((data) => {
    this.set('model', data.toArray()); // <-- here
  });
}
```

**Comment by buschtoens** [comment]
Also see https://github.com/offirgolan/ember-light-table/issues/272#issuecomment-263553870

**Comment by dmtask** [comment]
Thank you for your answer. :)

Yes, Cookbook I've read several times, unfortunately without result.

I have a `this.get ('model') when loading the data. PushObjects (records.content);` in it. `Records` includes the new model. This is what I did to avoid the table being reloaded.

With a `this.set ('model', records)` the model is reloaded and thus the table and you are back to the top. I would like to avoid this.

**Comment by buschtoens** [comment]
I assume you have defined your `table` property as computed property in dependence of `model`. This is an anti-pattern. Every time the `model` property is replaced, the `table` property is recomputed, i.e. you get a new table, thus the viewport appears to scroll back to the top.

Please click on the `</>` icon in the top right of the [Cookbook](https://offirgolan.github.io/ember-light-table/#/cookbook/client-side) to see the recommended code for setting up and searching tables.

![image](https://user-images.githubusercontent.com/834636/27038886-9341a9d0-4f8c-11e7-9daa-3b9e6110fa5b.png)

**Comment by buschtoens** [comment]
@offirgolan Maybe we should create a search example with infinite scrolling?

**Comment by dmtask** [comment]
Hi buschtoens,

no, my table is not a computed property anymore. I have declared it as shown in the documentation inside the init () process.

```
Let table = new Table (this.get ('columns'), this.get ('model'), {enableSync: this.get('enableSync')});
This.set ('table', table);
```

I will look at your link times, but I think we have here a very special application for the Light Table.

**Comment by buschtoens** [comment]
Just for the record: The initial error (`The result of a server query is immutable`) was fixed by the conversion via `toArray()`?

Now we're only talking about scroll reset?

**Comment by dmtask** [comment]
No. The error is still there. 

The scrolling works and the search works, but only separately. This is probably exactly what you just said.

I think I have to sleep there but once a night over it, I sign up again tomorrow.

**Comment by buschtoens** [comment]
I'll add an example for server-side searching and sorting to the cookbook soon. Tracking it here #433.

Have you been able to resolve your problems in the meantime?

**Comment by buschtoens** [comment]
Have you been able to solve your problems?

I forgot, that the [Simple Example](https://offirgolan.github.io/ember-light-table/#/) features server-side sorting. Filtering would be done in the same way. Does this already help you or do you require a dedicated example with a simple search form?

**Comment by dmtask** [comment]
No, but we create us a own Component for this special case. Thanks for you help.

**Comment by ethanrubio** [comment]
If anyone else runs into this issue, I solved this by adding `toArray()` to the model on the route (i.e. where you originally pass in the model to the simple-table component.

**Comment by Canertasan** [comment]
`The result of a server query (for all user types) is immutable. To modify contents, use toArray()`
My req is custom endpoint that basically find_by_user_name from rails side. Returning only 1 user.
I couldn't fix this with toArray() because the response only is single Model returning from rails.

my returning reponse:
```json
{
    "data": {
        "id": "127",
        "type": "users",
        "attributes": {
            "name": "dekati55",
            "winning_count": 0
        }
    }
}
```

When i try to make toArray() it basically says that there is not a function.
`: response.toArray is not a function`

Any idea?
