### ISSUE TITLE
Error on teardown Ember v3.2, due to resize-detector

### ISSUE THREAD

**Issue by bgentry** [offirgolan/ember-light-table#570]
After upgrading to Ember v3.2, I get the following error when my light table component is destroyed:

```
Error: Assertion Failed: Attempted to call .sendAction() with the action 'on-resize' on the destroyed object '<act@component:resize-detector::ember550>'.
```

The addon [ember-element-resize-detector](https://github.com/EmberSherpa/ember-element-resize-detector) appears to be a transitive dependency of this addon, coming from [ember-scrollable](https://github.com/alphasights/ember-scrollable). It also appears to be unmaintained as it hasn't seen an update in 2 years 😢

*edit: updated to reflect that this doesn't block rendering and only happens on destroy*

**Comment by bgentry** [comment]
The error also does not happen if I wait one tick before hiding my component in tests (i.e. just wrap in `Ember.run.next()`)

**Comment by jviney** [comment]
Fixed here

https://github.com/jviney/ember-element-resize-detector/commit/9546302fdc81c207365be9a144cb8e10cceb5f91

**Comment by fran-worley** [comment]
@bgentry I believe resize detector has been bumped since you raised this and I've certainly not hit upon this in my apps. Please respond if you're still having issues.

**Comment by arun-jerry** [comment]
We are still facing this issue even after upgrading ember-scrollable and moving the tests to Qunit
